export interface IMajorEvents {
  data: IMajorEventData[];
}

export interface IMajorEventData {
  year: string;
  month: string;
  day: string;
  zh_name: string;
  eng_name: string;
  jp_name: string;
  display: boolean;
  url?: string;
  type: "internal" | "external" | "pointer";
}

const majorEvents: IMajorEvents = {
  data: [
    {
      year: "2012",
      month: "2",
      day: "1",
      zh_name: "Buddy市開荒",
      eng_name: "Buddy City Development",
      jp_name: "Buddy 市開拓",
      display: true,
      type: "pointer",
    },
    {
      year: "2012",
      month: "2",
      day: "2",
      zh_name: "基礎道路建成",
      eng_name: "Construction of basic roads",
      jp_name: "基礎道路建設完了",
      display: true,
      type: "pointer",
    },
    {
      year: "2012",
      month: "2",
      day: "3",
      zh_name: "定義市政區-市中心，界定為(197,238)至(375,383)之間",
      eng_name:
        "Definition of Buddy Central, defined as (197,238) to (375,383)",
      jp_name: "市政区の定義 - 中央区、座標(197,238)から(375,383)まで",
      display: true,
      url: "/building_list/0",
      type: "internal",
    },
    {
      year: "2012",
      month: "2",
      day: "20",
      zh_name:
        "定義市政區-Buddy Hill，界定為(197,238)、(405,227)、(437,373)、(360,296)之間",
      eng_name:
        "Definition of Buddy Hill, defined as (197,238), (405,227), (437,373), (360,296), later renamed Buddy Hill District",
      jp_name:
        "市政区の定義 - Buddy 山、座標(197,238)、(405,227)、(437,373)、(360,296)から、後にBuddy 山区と改名",
      display: true,
      url: "/building_list/0",
      type: "internal",
    },
    {
      year: "2012",
      month: "3",
      day: "1",
      zh_name: "建立路名系統",
      eng_name: "Establishment of a road naming system",
      jp_name: "道路名システムの確立",
      display: true,
      type: "pointer",
    },
    {
      year: "2012",
      month: "3",
      day: "15",
      zh_name: "Buddy City 火箭發射中心落成",
      eng_name: "Completion of Buddy City Space Center Center",
      jp_name: "Buddy市射場前駅竣工",
      display: true,
      url: "/building_list/0/20",
      type: "internal",
    },
    {
      year: "2012",
      month: "3",
      day: "16",
      zh_name:
        "行使衛星發射升空，搭載全球定位系統、氣像監測設備，位置為(293,345)至(311,363)之間上空",
      eng_name:
        "Satellite launch for global positioning system and weather monitoring equipment, located between (293,345) and (311,363)",
      jp_name:
        "衛星発射の実施、全地球測位システムおよび気象監視装置を搭載し、座標(293,345)から(311,363)までの上空",
      display: true,
      type: "pointer",
    },
    {
      year: "2012",
      month: "3",
      day: "20",
      zh_name: "Buddy City體育館落成",
      eng_name: "Completion of Tsing Yi Sports Centre",
      jp_name: "Buddy 市体育館竣工",
      display: true,
      url: "/building_list/0/3",
      type: "internal",
    },
    {
      year: "2012",
      month: "3",
      day: "25",
      zh_name: "Buddy City天文台落成，現Buddy City暨DJaLok天文台",
      eng_name:
        "Completion of Buddy City Observatory, now Buddy City Observation by DJaLok",
      jp_name: "Buddy 市天文台竣工、現在は Buddy 市 DJaLok 気象局",
      display: true,
      url: "/building_list/1/6",
      type: "internal",
    },
    {
      year: "2012",
      month: "3",
      day: "27",
      zh_name: "前九廣鐵路鐘樓建成",
      eng_name: "Reappearance of the Former Kowloon-Canton Railway Clock Tower",
      jp_name: "前九広鉄路鐘楼竣工",
      display: true,
      url: "/building_list/0/0",
      type: "internal",
    },
    {
      year: "2012",
      month: "4",
      day: "1",
      zh_name: "高架鐵路一線第一期完工通車",
      eng_name: "Completion of Phase 1 of the Elevated Railway Line One",
      jp_name: "高架鉄道一線第一期が完成し開通",
      display: false,
      url: "/history/railway-history/0",
      type: "internal",
    },
    {
      year: "2012",
      month: "4",
      day: "1",
      zh_name: "高架鐵路一線正式通車",
      eng_name: "Official launch of Elevated Railway Line One",
      jp_name: "高架鉄道一線第一期が正式に開通",
      display: true,
      url: "/history/railway-history/0",
      type: "internal",
    },
    {
      year: "2012",
      month: "5",
      day: "1",
      zh_name: "Buddy City電視城落成",
      eng_name: "Completion of Buddy City Television City",
      jp_name: "Buddy 市テレビ本部竣工",
      display: true,
      url: "/building_list/0/6",
      type: "internal",
    },
    {
      year: "2012",
      month: "5",
      day: "2",
      zh_name: "高架鐵路二線第一期完工通車",
      eng_name: "Completion of Phase 1 of Elevated Railway Line Two",
      jp_name: "高架鉄道二線第一期が完成し開通",
      display: false,
      url: "/history/railway-history/1",
      type: "internal",
    },
    {
      year: "2012",
      month: "5",
      day: "2",
      zh_name: "高架鐵路二線正式通車",
      eng_name: "Official launch of Elevated Railway Line Two",
      jp_name: "高架鉄道二線が正式に開通",
      display: true,
      url: "/history/railway-history/1",
      type: "internal",
    },
    {
      year: "2012",
      month: "5",
      day: "3",
      zh_name: "地下鐵路一線正式通車",
      eng_name: "Official launch of Mass Transit Railway Line One",
      jp_name: "地下鉄一線が正式に開通",
      display: true,
      url: "/history/railway-history/2",
      type: "internal",
    },
    {
      year: "2012",
      month: "5",
      day: "4",
      zh_name: "高架鐵路一線第二期喪屍場延線完工通車",
      eng_name:
        "Completion of Phase 2 of Elevated Railway Line One Zombie Ground Extension",
      jp_name: "高架鉄道一線第二期ゾンビ場延伸が完成し開通",
      display: false,
      url: "/history/railway-history/3",
      type: "internal",
    },
    {
      year: "2013",
      month: "5",
      day: "5",
      zh_name: "高架鐵路一線第二期Super Restaurant延線完工通車",
      eng_name:
        "Completion of Phase 2 of Elevated Railway Line One Super Restaurant Extension",
      jp_name: "高架鉄道一線第二期Super Restaurant延伸が完成し開通",
      display: false,
      url: "/history/railway-history/3",
      type: "internal",
    },
    {
      year: "2013",
      month: "5",
      day: "10",
      zh_name: "Buddy City 電車總站落成",
      eng_name: "Completion of Buddy City Train Terminus",
      jp_name: "Buddy 市電車終着駅竣工",
      display: true,
      url: "/building_list/0/7",
      type: "internal",
    },
    {
      year: "2013",
      month: "5",
      day: "11",
      zh_name: "定義市政區-北區、沙漠區",
      eng_name: "Definition of North District, Desert District",
      jp_name: "市政区の定義 - 北区、砂漠区",
      display: true,
      url: "/building_list/2",
      type: "internal",
    },
    {
      year: "2013",
      month: "7",
      day: "2",
      zh_name: "定義市政區-沙田區",
      eng_name: "Definition of Sha Tin District",
      jp_name: "市政区の定義 - 沙田区",
      display: true,
      url: "/building_list/9",
      type: "internal",
    },
    {
      year: "2017",
      month: "4",
      day: "1",
      zh_name: "定義市政區-東京區，取代部份沙漠區",
      eng_name:
        "Definition of Tokyo District, replacing part of the Desert District",
      jp_name: "市政区の定義 - 東京区、一部砂漠区を取って代わる。",
      display: true,
      url: "/building_list/4",
      type: "internal",
    },
    {
      year: "2017",
      month: "4",
      day: "2",
      zh_name: "香港中國銀行香港大廈落成",
      eng_name: "Completion of Bank of China Hong Kong Building",
      jp_name: "香港中国銀行タワー、東京タワー竣工",
      display: true,
      url: "/building_list/11/2",
      type: "internal",
    },
    {
      year: "2017",
      month: "4",
      day: "2",
      zh_name: "東京タワー落成",
      eng_name: "Completion of Tokyo Tower",
      jp_name: "",
      display: true,
      url: "/building_list/4/2",
      type: "internal",
    },
    {
      year: "2017",
      month: "4",
      day: "10",
      zh_name:
        "定義市政區-清水區，界定為現由黑目川以北、東京タワー通り以東、大阪城以西區域",
      eng_name:
        "Definition of Kiyo Mizu District, defined as the area north of Meguro Gawa, east of Tokyo Tower Street, and west of Osaka Castle",
      jp_name:
        "市政区の定義 - 清水区、現在は黒目川以北、東京タワー通り以東、大阪城以西のエリア",
      display: true,
      url: "/building_list/5",
      type: "internal",
    },
    {
      year: "2017",
      month: "4",
      day: "11",
      zh_name: "定義市政區-樂園區，界定為現港島區、校園區以南、臺北區以北區域",
      eng_name:
        "Definition of Paradise District, defined as the area south of Hong Kong Island District, north of Campus District",
      jp_name:
        "市政区の定義 - 楽園区、現在は港島区、学園区以南、台北区以北のエリア",
      display: true,
      url: "/building_list/8",
      type: "internal",
    },
    {
      year: "2017",
      month: "4",
      day: "13",
      zh_name: "香港中央圖書館落成",
      eng_name: "Completion of Hong Kong Central Library",
      jp_name: "香港中央図書館竣工",
      display: true,
      url: "/building_list/11/3",
      type: "internal",
    },
    {
      year: "2017",
      month: "4",
      day: "15",
      zh_name: "RoyHo 清水寺落成",
      eng_name: "Completion of Kiyomizu Temple by RoyHo",
      jp_name: "RoyHo清水寺竣工",
      display: true,
      url: "/building_list/8/0",
      type: "internal",
    },
    {
      year: "2017",
      month: "4",
      day: "16",
      zh_name: "建立地址系統、定義市政區-新市中心區，取代部份市中心區域",
      eng_name:
        "Establishment of an address system, definition of New Buddy Central District, replacing part of the Buddy Central District.",
      jp_name:
        "住所システムの確立、市政区の定義 - 新中央区、一部中央区および Buddy 山区に代わる",
      display: true,
      url: "/building_list/0",
      type: "internal",
    },
    {
      year: "2017",
      month: "4",
      day: "16",
      zh_name: "Buddy Hill 更名為 Buddy 山區",
      eng_name: "Renaming Buddy Hill to Buddy Hill District.",
      jp_name: "Buddy山をBuddy山区に変更いたしました。",
      display: true,
      url: "/building_list/1",
      type: "internal",
    },
    {
      year: "2017",
      month: "4",
      day: "19",
      zh_name: "旋轉木馬搬遷到通天列車以南、樂園區一部份被港島區替代",
      eng_name:
        "Relocation of the Merry-Go-Round Carousel to the south of the Sky Goes Roller Coaster, replacement of a part of the Paradise ",
      jp_name:
        "メリーゴーラウンドがスカイ・ゴーズ・ローラーコースターの南に移設され、楽園区の一部が港島区に置き換えられ。",
      display: true,
      url: "/building_list/8/1",
      type: "internal",
    },
    {
      year: "2017",
      month: "4",
      day: "19",
      zh_name:
        "定義市政區-港島區，取代樂園區，界定為現東京タワー通り以南、新中央區以南、樂園區以東區域",
      eng_name:
        "District with the Hong Kong Island District, definition of the Hong Kong Island District, defined as the area south of Tokyo Tower Street, south of the New Central District, and east of the Paradise District",
      jp_name:
        "市政区の定義 - 港島区、現在は東京タワー通り以南、新中央区以南、楽園区以東のエリア",
      display: true,
      url: "/building_list/11",
      type: "internal",
    },
    {
      year: "2017",
      month: "4",
      day: "20",
      zh_name:
        "定義市政區-青衣區，取代北區。界定為由現青敬路以西、校園路以北等區域",
      eng_name:
        "District with the Tsing Yi District, replacing North District, defined as the area west of Tsing King Road and north of Campus Road.",
      jp_name:
        "市政区の定義 - 青衣区、北区に取って代わる。現在は青敬路以西、学園路以北などのエリア",
      display: true,
      url: "/building_list/6",
      type: "internal",
    },
    {
      year: "2017",
      month: "4",
      day: "20",
      zh_name: "青衣運動場建成",
      eng_name: "Completion of Tsing Yi Sports Centre.",
      jp_name: "青衣運動場竣工",
      display: true,
      url: "/building_list/6/0",
      type: "internal",
    },
    {
      year: "2017",
      month: "4",
      day: "30",
      zh_name: "Buddy City 海濱公園落成",
      eng_name: "Completion of Buddy City Promenade",
      jp_name: "Buddy 市海浜公園竣工",
      display: true,
      url: "/building_list/11/0",
      type: "internal",
    },
    {
      year: "2017",
      month: "5",
      day: "10",
      zh_name: "定義市政區-機場管轄區，取代部份沙漠區",
      eng_name:
        "Definition of Airport Control Area, replacing part of the Desert District",
      jp_name: "市政区の定義 - 空港管轄区、一部砂漠区に取って代わる",
      display: true,
      url: "/building_list/7",
      type: "internal",
    },
    {
      year: "2017",
      month: "5",
      day: "15",
      zh_name: "高架鐵路一線第三期電車總站延線完工通車",
      eng_name:
        "Completion of Phase 3 of Elevated Railway Line One Train Terminus Extension",
      jp_name: "高架鉄道一線第三期電車總站延伸が完成し開通",
      display: false,
      url: "/history/railway-history/4",
      type: "internal",
    },
    {
      year: "2017",
      month: "5",
      day: "15",
      zh_name: "定義市政區-能源區",
      eng_name: "Definition of Energy District",
      jp_name: "市政区の定義 - エネルギー区",
      display: true,
      url: "/building_list/10",
      type: "internal",
    },
    {
      year: "2017",
      month: "5",
      day: "16",
      zh_name: "Buddy City暨Kai's 國際機場落成啟用",
      eng_name:
        "Completion of Buddy City International Airport by Kai and commencement.",
      jp_name: "Buddy市Kai国際空港竣工運用開始",
      display: true,
      url: "/building_list/7/0",
      type: "internal",
    },
    {
      year: "2017",
      month: "5",
      day: "16",
      zh_name: "Buddy City核電站落成啟用",
      eng_name: "Completion of Buddy City Nuclear Disaster and commencement",
      jp_name: "Buddy市立原子力発電所竣工運用開始",
      display: true,
      url: "/building_list/10/0",
      type: "internal",
    },
    {
      year: "2017",
      month: "5",
      day: "20",
      zh_name: "青馬大橋建成",
      eng_name: "Completion of Tsing Ma Bridge",
      jp_name: "青馬大橋竣工",
      display: true,
      url: "/building_list/7/2",
      type: "internal",
    },
    {
      year: "2017",
      month: "5",
      day: "20",
      zh_name: "定義市鎮-新Buddy市",
      eng_name: "Definition of New Buddy City",
      jp_name: "市町の定義 - 新Buddy 市",
      display: true,
      type: "pointer",
    },
    {
      year: "2017",
      month: "5",
      day: "22",
      zh_name: "海底隧道落成啟用",
      eng_name: "Completion of the Cross-Harbou tunnel and commencement",
      jp_name: "水底トンネル竣工運用開始",
      display: true,
      url: "/building_list/10/1",
      type: "internal",
    },
    {
      year: "2017",
      month: "6",
      day: "1",
      zh_name: "路面電車第一期完工通車",
      eng_name: "Completion of Phase 1 of Tramways",
      jp_name: "路面電車第一期が完成し開通",
      display: false,
      url: "/history/railway-history/5",
      type: "internal",
    },
    {
      year: "2017",
      month: "6",
      day: "1",
      zh_name: "路面電車正式通車",
      eng_name: "Official launch of Tramways",
      jp_name: "路面電車が正式に開通",
      display: true,
      url: "/history/railway-history/5",
      type: "internal",
    },
    {
      year: "2017",
      month: "6",
      day: "2",
      zh_name: "定義市政區-校園區。界定為由現校園路以南、中央廣場路以西等區域",
      eng_name:
        "Definition of Campus District, defined as the area south of Campus Road, west of Central Plaza Road.",
      jp_name:
        "市政区の定義 - 学園区、現在は学園路以南、中央広場路以西などのエリア",
      display: true,
      url: "/building_list/3",
      type: "internal",
    },
    {
      year: "2017",
      month: "6",
      day: "6",
      zh_name: "梁植偉(樂善堂梁植偉紀念中學校舍)落成",
      eng_name:
        "Completion of LCW (Lok Sin Tong Leung Chik Wai Memorial School Campus)",
      jp_name: "梁植偉竣工",
      display: true,
      url: "/building_list/3/0",
      type: "internal",
    },
    {
      year: "2017",
      month: "6",
      day: "10",
      zh_name: "機場快線第一期完工通車",
      eng_name: "Completion of Phase 1 of Airport Express",
      jp_name: "空港快線第一期が完成し開通",
      display: false,
      url: "/history/railway-history/6",
      type: "internal",
    },
    {
      year: "2017",
      month: "6",
      day: "10",
      zh_name: "機場快線正式通車",
      eng_name: "Official launch of Airport Express",
      jp_name: "空港快線が正式に開通",
      display: true,
      url: "/history/railway-history/6",
      type: "internal",
    },
    {
      year: "2017",
      month: "6",
      day: "20",
      zh_name: "路面電車第二期Buddy City運動場及沙田區延線完工通車",
      eng_name:
        "Completion of Phase 2 of Tramways Buddy City Sports Centre and Sha Tin District Extension",
      jp_name: "路面電車第二期Buddy 市立運動場および沙田区延伸が完成し開通",
      display: false,
      url: "/history/railway-history/7",
      type: "internal",
    },
    {
      year: "2017",
      month: "6",
      day: "20",
      zh_name: "St.Mok M大教堂落成",
      eng_name: "Completion of St.Mok M Church",
      jp_name: "St.Mok M 教会堂竣工",
      display: true,
      url: "/building_list/1/10",
      type: "internal",
    },
    {
      year: "2017",
      month: "6",
      day: "21",
      zh_name: "定義市政區-軍營區",
      eng_name: "Definition of Barracks District",
      jp_name: "市政区の定義 - 兵営区",
      display: true,
      type: "pointer",
    },
    {
      year: "2017",
      month: "6",
      day: "25",
      zh_name: "浩園落成",
      eng_name: "Completion of Gallant Garden",
      jp_name: "浩園竣工",
      display: true,
      url: "/building_list/1/11",
      type: "internal",
    },
    {
      year: "2017",
      month: "7",
      day: "12",
      zh_name: "路面電車第三期清水區延線完工通車",
      eng_name:
        "Completion of Phase 3 of Tramways Kiyo Mizu District Extension",
      jp_name: "路面電車第三期清水区延伸が完成し開通",
      display: false,
      url: "/history/railway-history/8",
      type: "internal",
    },
    {
      year: "2017",
      month: "11",
      day: "11",
      zh_name:
        "定義市政區-大阪區，取代北區。界定為由現清水路以北、本町通以北、Buddy山徑以北等區域",
      eng_name:
        "Definition of Osaka District, replacing North District, defined as the area north of Kiyo Mizu Road, north of Hommachi Dori, north of Buddy Hill Path.",
      jp_name:
        "市政区の定義 - 大阪区、北区に取って代わる。現在は清水路以北、本町通以北、Buddy 山道以北などのエリア",
      display: true,
      url: "/building_list/12",
      type: "internal",
    },
    {
      year: "2017",
      month: "11",
      day: "13",
      zh_name: "大阪城落成",
      eng_name: "Completion of Osaka Castle",
      jp_name: "大阪城竣工",
      display: true,
      url: "/building_list/12/8",
      type: "internal",
    },
    {
      year: "2017",
      month: "11",
      day: "15",
      zh_name: "大阪城公園周邊建設落成",
      eng_name: "Completion of construction around Osaka Castle Park",
      jp_name: "大阪城公園周辺の建設が完成",
      display: true,
      url: "/building_list/12/0",
      type: "internal",
    },
    {
      year: "2017",
      month: "11",
      day: "20",
      zh_name: "開始建立觀光服務網站Buddy-Info",
      eng_name: "Initiation of Buddy-Info Visitors' Guide Website",
      jp_name: "観光情報サイトBuddy-Infoの構築開始",
      display: true,
      type: "pointer",
    },
    {
      year: "2017",
      month: "11",
      day: "25",
      zh_name: "財團法人Buddy市觀光局正式成立",
      eng_name: "Official establishment of the Buddy City Tourism Bureau",
      jp_name: "Buddy市観光局法人が正式に設立",
      display: true,
      url: "/bcctb-about-us",
      type: "internal",
    },
    {
      year: "2018",
      month: "2",
      day: "1",
      zh_name: "Buddy City路面電車進行大型延展工程",
      eng_name: "Expansion project for Buddy City Tramways",
      jp_name: "Buddy 市路面電車が大規模な拡張工事を実施",
      display: true,
      url: "/history/railway-history/9",
      type: "internal",
    },
    {
      year: "2018",
      month: "3",
      day: "3",
      zh_name: "路面電車第四期港島區、能源區及跨海線路延線完工通車",
      eng_name:
        "Completion of Phase 4 of Tramways in Hong Kong Island District, Energy District, and Cross-Harbor route",
      jp_name:
        "路面電車第四期が港島区、エネルギー区およびクロスハーバールート延伸が完成し開通",
      display: false,
      url: "/history/railway-history/9",
      type: "internal",
    },
    {
      year: "2018",
      month: "4",
      day: "1",
      zh_name: "修建目黒川水道",
      eng_name: "Construction of the Meguro Gawa Waterway",
      jp_name: "目黒川水道の建設",
      display: true,
      url: "/building_list/4/6",
      type: "internal",
    },
    {
      year: "2018",
      month: "4",
      day: "2",
      zh_name: "目黒川沿いの桜並木修建完工",
      eng_name: "Completion of cherry blossoms along the Megurogawa",
      jp_name: "目黒川沿いの桜並木の建設が完成",
      display: true,
      url: "/building_list/4/6",
      type: "internal",
    },
    {
      year: "2018",
      month: "4",
      day: "5",
      zh_name: "基督教醫療財團法人Buddy醫院落成",
      eng_name: "Completion of the Buddy Christianity Hospital",
      jp_name: "Buddy病院竣工",
      display: true,
      url: "/building_list/13/0",
      type: "internal",
    },
    {
      year: "2018",
      month: "4",
      day: "10",
      zh_name: "臺北101落成",
      eng_name: "Completion of Taipei 101",
      jp_name: "台北101竣工",
      display: true,
      url: "/building_list/13/2",
      type: "internal",
    },
    {
      year: "2018",
      month: "4",
      day: "15",
      zh_name: "Buddy市警察廳本部落成",
      eng_name: "Completion of Buddy City Police Department Headquarters",
      jp_name: "Buddy 市警察庁本部竣工",
      display: true,
      url: "/building_list/12/5",
      type: "internal",
    },
    {
      year: "2018",
      month: "4",
      day: "20",
      zh_name: "Buddy市廳落成",
      eng_name: "Completion of Buddy City Government Offic",
      jp_name: "Buddy 市庁竣工",
      display: true,
      url: "/building_list/12/6",
      type: "internal",
    },
    {
      year: "2018",
      month: "4",
      day: "25",
      zh_name: "Buddy市消防廳本部落成",
      eng_name: "Completion of Buddy City Fire Department Headquarters",
      jp_name: "Buddy 市消防庁本部竣工",
      display: true,
      url: "/building_list/4/7",
      type: "internal",
    },
    {
      year: "2018",
      month: "5",
      day: "3",
      zh_name: "高架鐵路二線第二期青衣區延線完工通車",
      eng_name:
        "Completion of Phase 2 of Elevated Railway Line Two in Tsing Yi District.",
      jp_name: "高架鉄道二線第二期青衣区延伸が完成し開通",
      display: false,
      url: "/history/railway-history/10",
      type: "internal",
    },
    {
      year: "2018",
      month: "5",
      day: "3",
      zh_name:
        "市營地下鐵中央線第一期正式通車、市營地下鐵阪源線第一期正式通車、市營地下鐵清水沙田線第一期正式通車",
      eng_name:
        "Opening of Phase 1 of the Municipal Subway Central Line, opening of Phase 1 of the Municipal Subway Hangen Line, opening of Phase 1 of the Municipal Subway Kiyo Mizu Sha Tin Line.",
      jp_name:
        "市営地下鉄中央線第一期が正式に開通、市営地下鉄阪源線第一期が正式に開通、市営地下鉄清水沙田線第一期が正式に開通",
      display: false,
      url: "/history/railway-history/10",
      type: "internal",
    },
    {
      year: "2018",
      month: "5",
      day: "3",
      zh_name: "市營地下鐵中央線、阪源線、清水沙田線正式通車",
      eng_name:
        "Official launch of the Municipal Subway's Central Line, Hangen Line, Kiyo Mizu Sha Tin Line",
      jp_name: "市営地下鉄の中央線、阪源線、清水沙田線が正式に開通",
      display: true,
      url: "/history/railway-history/10",
      type: "internal",
    },
    {
      year: "2018",
      month: "7",
      day: "5",
      zh_name:
        "機場快線第二期東京沙漠、沙田、大阪延線完工通車。路面電車第五期大阪區、目黑川及臺北區延線完工通車。",
      eng_name:
        "Completion of Phase 2 of Airport Express to Tokyo Desert, Sha Tin, and Osaka.",
      jp_name: "空港快線第二期東京砂漠、沙田、大阪延伸が完成し開通",
      display: false,
      url: "/history/railway-history/11",
      type: "internal",
    },
    {
      year: "2018",
      month: "7",
      day: "15",
      zh_name: "機場快線直通車正式通車",
      eng_name: "Official launch of Airport Express Express Service",
      jp_name: "空港快線急行車が正式に開通",
      display: true,
      url: "/history/railway-history/11",
      type: "internal",
    },
    {
      year: "2018",
      month: "10",
      day: "2",
      zh_name: "宏福花園落成",
      eng_name: "Completion of Tivoli Garden",
      jp_name: "宏福花園竣工",
      display: true,
      url: "/building_list/6/2",
      type: "internal",
    },
    {
      year: "2018",
      month: "10",
      day: "4",
      zh_name: "青衣海濱公園修建完工",
      eng_name: "Completion of Tsing Yi Promenade",
      jp_name: "青衣海浜公園の建設が完成",
      display: true,
      url: "/building_list/6/8",
      type: "internal",
    },
    {
      year: "2018",
      month: "10",
      day: "19",
      zh_name: "青衣市政大廈落成",
      eng_name: "Completion of Tsing Yi Municipal Services Building",
      jp_name: "青衣市営サービスビル竣工",
      display: true,
      url: "/building_list/6/4",
      type: "internal",
    },
    {
      year: "2018",
      month: "10",
      day: "28",
      zh_name: "路面電車第六期青衣區延線完工通車",
      eng_name: "Completion of Phase 6 of Tramways in Tsing Yi District",
      jp_name: "路面電車第六期青衣区延伸が完成し開通",
      display: false,
      url: "/history/railway-history/12",
      type: "internal",
    },
    {
      year: "2018",
      month: "11",
      day: "9",
      zh_name: "定義市政區-臺北區。界定為由現軍營區以西、樂園區以南區域",
      eng_name:
        "Definition of Taipei District, defined as the area west of the Barracks District, south of the Paradise District",
      jp_name: "市政区の定義 - 台北区、現在は兵営区以西、楽園区以南のエリア",
      display: true,
      url: "/building_list/13",
      type: "internal",
    },
    {
      year: "2021",
      month: "9",
      day: "22",
      zh_name:
        "定義市水域-維多利亞港，界定為現軍營區以東、海盜船以南水域。東京灣，界定海盜船以東，機場以西至能源區以東水域為止",
      eng_name:
        "Definition of sea area - Victoria Harbour, defined as the area east of the Barracks District, south of the Pirate Ship. Tokyo Bay, defined as the area east of the Pirate Ship, west of the Airport, and east of the Energy District.",
      jp_name:
        "水域の定義 - ビクトリア・ハーバー、現在は兵営区以東、海賊船以南の水域。東京湾、海賊船以東、空港以西からエネルギー区以東の水域に至る。",
      display: true,
      type: "pointer",
    },
    {
      year: "2021",
      month: "10",
      day: "31",
      zh_name: "鐵路轉乘重組",
      eng_name: "Reorganization of interchange station",
      jp_name: "鉄道の乗り換え再編",
      display: false,
      url: "/history/railway-history/13",
      type: "internal",
    },
    {
      year: "2021",
      month: "12",
      day: "1",
      zh_name: "建立年號「友平」，諭意友好及和平，並以2012年為元年",
      eng_name:
        'Establishment of the era name "BUDDY" signifying friendship and peace, with the first year starting in 2012',
      jp_name: "年号「友平」の設立、友好と平和の意味を持ち、2012年を元年とする",
      display: true,
      url: "/page/basic/calendar-system-and-city-song",
      type: "internal",
    },
    {
      year: "2022",
      month: "1",
      day: "1",
      zh_name: "祝賀Buddy市成立10周年",
      eng_name: "Celebration of the 10th anniversary of Buddy City's founding",
      jp_name: "Buddy 市の設立10周年を祝う",
      display: true,
      type: "pointer",
    },
    {
      year: "2022",
      month: "6",
      day: "12",
      zh_name:
        "出現十年一遇大地震，因地殼變動而多處出現斷層，是 Buddy 市建立以來最大規模的一次災難。",
      eng_name:
        "Occurrence of a once-in-a-decade major earthquake, resulting in multiple fault lines due to crustal movement, the largest disaster since the establishment of Buddy City",
      jp_name:
        "0年に一度の大地震が発生し、地殻変動により多くの断層が発生、Buddy 市建設以来の最大規模の災害となった。",
      display: true,
      type: "pointer",
    },
    {
      year: "2022",
      month: "6",
      day: "13",
      zh_name: "Buddy 山隧道、清水隧道落成啟用",
      eng_name: "Opening and use of Buddy Hill Tunnel and Kiyo Mizu Tunnel",
      jp_name: "Buddy 山トンネル、清水トンネル竣工および運用開始",
      display: true,
      type: "pointer",
    },
    {
      year: "2022",
      month: "6",
      day: "14",
      zh_name: "市中心地下街落成",
      eng_name: "Completion of the underground street in the Buddy Central",
      jp_name: "中央区地下街が完成",
      display: true,
      type: "pointer",
    },
    {
      year: "2022",
      month: "6",
      day: "22",
      zh_name: "定義市政區-京都區，界定為清水區以東、東京區以東、沙漠區以東",
      eng_name:
        "Definition of Kyoto District, defined as the area east of Kiyo Mizu District, east of Tokyo District, and east of the Desert District",
      jp_name:
        "市政区の定義 - 京都区、現在は清水区以東、東京区以東、砂漠区以東",
      display: true,
      url: "/building_list/14",
      type: "internal",
    },
    {
      year: "2022",
      month: "6",
      day: "23",
      zh_name: "法觀寺（八坂塔）重見天日",
      eng_name: "Reappearance of Hokanji Temple (Yasaka Pagoda)",
      jp_name: "法観寺（八坂の塔）が再び日の目を見る",
      display: true,
      url: "/building_list/14/0",
      type: "internal",
    },
    {
      year: "2022",
      month: "6",
      day: "24",
      zh_name: "音羽山清水寺重見天日",
      eng_name: "Reappearance of Otowayama Kiyomizu Dera",
      jp_name: "音羽山清水寺が再び日の目を見る",
      display: true,
      url: "/building_list/14/1",
      type: "internal",
    },
    {
      year: "2022",
      month: "7",
      day: "1",
      zh_name: "修建道頓堀水道",
      eng_name: "Construction of the Dotombori Waterway",
      jp_name: "道頓堀水路の建設",
      display: true,
      url: "/building_list/12/12",
      type: "internal",
    },
    {
      year: "2022",
      month: "7",
      day: "1",
      zh_name: "道頓堀周邊景點落成",
      eng_name: "Completion of attractions around Dotombori",
      jp_name: "道頓堀周辺の観光スポットが完成",
      display: true,
      url: "/building_list/12/20",
      type: "internal",
    },
    {
      year: "2022",
      month: "7",
      day: "3",
      zh_name:
        "市營地下鐵中央線第二期谷町四丁目至難波延線段完工通車。雙京阪線第一期清水至京都延線段及黑目川至沙漠東京延線段完工，市營地下鐵清水沙田線重劃線路並廢線，由雙京坂線代替正式通車。市營地下鐵清源線第一期完工，市營地下鐵阪源線重劃線路，由清源線代替正式通車。路面電車第七期京都區、大阪區道頓堀延線完工通車。",
      eng_name:
        "Opening of Phase 2 of the Municipal Subway Central Line from Tanimachi Yochome to Nanba, completion of the Kyoto Extension Line from Kiyomizu to Kyoto, and the Megou Gawa to the Desert Tokyo Extension Line, closure and replacement of the Municipal Subway Kiyo Mizu Sha Tin Line with the Futa Keihan Line, opening of the Kiyo Gen Line, reclassification of the Municipal Subway Hangen Line as the Municipal Subway Kiyo Gen Line",
      jp_name:
        "市営地下鉄中央線第二期、谷町四丁目から難波延伸区間が完成し開通、双京阪線第一期、清水から京都延伸区間および黒目川から砂漠東京延伸区間が完成、市営地下鉄清水沙田線が再線路化され、双京坂線に代わって正式に開通、清源線第一期が完成し、市営地下鉄阪源線再線路化区間が清源線に代わって正式に開通、路面電車第七期京都区、大阪区、道頓堀延伸区間が完成し開通",
      display: false,
      url: "/history/railway-history/14",
      type: "internal",
    },
    {
      year: "2022",
      month: "7",
      day: "3",
      zh_name:
        "市營地下鐵清水沙田線重劃線路並廢線，由雙京坂線代替正式通車。市營地下鐵阪源線重劃線路，由清源線代替正式通車。",
      eng_name:
        "The Municipal Subway Kiyo Mizu Sha Tin Line was reconfigured and discontinued, replaced by the Futa Keihan Line, which was officially opened. The Municipal Subway Hangen Line was also reconfigured, replaced by the Kiyo Gen Line, which was officially opened.",
      jp_name:
        "市営地下鉄清水沙田線の再線路化および廃止し、双京坂線に代わって正式に開通しました。また、市営地下鉄阪源線の再線路化も行い、清源線に代わって正式に開通いたしました。",
      display: true,
      url: "/history/railway-history/14",
      type: "internal",
    },
    {
      year: "2022",
      month: "7",
      day: "10",
      zh_name:
        "BUDDY市政府正式發佈代表BUDDY市的市歌，名為《友與平》。諭意為「友好及和平」與年號一樣，祝願BUDDY市和全宇宙的人能友好與和平地生活。",
      eng_name:
        'The BUDDY City Government officially announces the city\'s anthem, titled "Friendship and Peace" which bears the same meaning as the era name, signifying "friendship and peace" It is a wish for BUDDY City and all inhabitants of the universe to live in friendship and peace.',
      jp_name:
        "BUDDY市政府は正式にBUDDY市の市歌を発表し、その名は「友と平（ともとへい）」といいます。「友好及び和平」という意味で、年号と同様に、BUDDY市および宇宙全体の人々が友好的で平和に暮らせることを祈っています。",
      display: true,
      url: "/page/basic/calendar-system-and-city-song",
      type: "internal",
    },
    {
      year: "2022",
      month: "7",
      day: "17",
      zh_name: "大阪クリスタルタワー完工開張。",
      eng_name: "Completion of Osaka Crystal Tower",
      jp_name: "大阪クリスタルタワーが竣工およびオープン",
      display: true,
      url: "/building_list/12/25",
      type: "internal",
    },
    {
      year: "2022",
      month: "7",
      day: "17",
      zh_name:
        "市營地下鐵中央線與雙京坂線於谷町四丁目相接直通運轉，市營地下鐵清源線第二期清水至大阪商業園區延線段完工，市營地下鐵清源線，重新覆蓋大阪區，更名為阪源綠地線正式通車。路面電車第八期大阪商業園區延線段完工通車。",
      eng_name:
        "Integration of the Municipal Subway Central Line and Futa Keihan Line at Tanimachi Yochome.  Completion of Phase 2 of the Municipal Subway Kiyo Gen Line Extension from Kiyomizu to Osaka Business Park.  Reconfiguration of the Municipal Subway kiyo Gen Line, covering Osaka District again, and renaming it as the Municipal Subway Hangen Ryokuchi Line, officially opened. Completion of Phase 8 of Tramways Extension in Osaka Business Park.",
      jp_name:
        "市営地下鉄中央線と双京坂線が谷町四丁目で接続して直通運転を開始、市営地下鉄清源線第二期、清水から大阪ビジネスパーク延伸区間が完成し開通、市営地下鉄清源線が再び大阪区をカバーし、阪源緑地線に改名して正式に開通、路面電車第八期大阪ビジネスパーク延伸区間が完成し開通",
      display: false,
      url: "/history/railway-history/15",
      type: "internal",
    },
    {
      year: "2022",
      month: "7",
      day: "17",
      zh_name:
        "市營地下鐵中央線與雙京坂線於谷町四丁目相接直通運轉，市營地下鐵清源線，重新覆蓋大阪區，更名為阪源綠地線正式通車。",
      eng_name:
        "Integration of the Municipal Subway Central Line and Futa Keihan Line at Tanimachi Yochome.   Reconfiguration of the Municipal Subway kiyo Gen Line, covering Osaka District again, and renaming it as the Municipal Subway Hangen Ryokuchi Line, officially opened.",
      jp_name:
        "市営地下鉄中央線と双京坂線が谷町四丁目で接続して直通運転を開始、市営地下鉄清源線が再び大阪区をカバーし、阪源緑地線に改名して正式に開通",
      display: true,
      url: "/history/railway-history/15",
      type: "internal",
    },
    {
      year: "2022",
      month: "7",
      day: "30",
      zh_name: "大阪 HEP FIVE 及大阪梅田周邊景點落成。",
      eng_name:
        "Completion of Osaka HEP FIVE and attractions around Osaka Umeda.",
      jp_name: "大阪 HEP FIVE および大阪梅田周辺の観光スポットが完成",
      display: true,
      url: "/building_list/12/27",
      type: "internal",
    },
    {
      year: "2022",
      month: "8",
      day: "7",
      zh_name: "青衣公園落成。",
      eng_name: "Completion of Tsing Yi Park",
      jp_name: "青衣公園竣工",
      display: true,
      url: "/building_list/6/3",
      type: "internal",
    },
    {
      year: "2022",
      month: "8",
      day: "7",
      zh_name:
        "市營地下鐵雙京坂線第三期東梅田站完工通車。市營地下鐵御堂筋線第一期完工通車。路面電車第九期大阪梅田區域延線段完工通車。",
      eng_name:
        "Opening of Phase 3 of the Municipal Subway Futa Keihan Line at Higashi Umeda Station, Completion of Phase 1 of the Municipal Subway Mido Suji Line, Opening of Phase 9 of Tramways Extension to HEP FIVE",
      jp_name:
        "市営地下鉄双京坂線第三期、東梅田駅が完成し開通、市営地下鉄御堂筋線第一期が完成し開通、路面電車第九期 HEP FIVE 延伸区間が完成し開通",
      display: false,
      url: "/history/railway-history/16",
      type: "internal",
    },
    {
      year: "2022",
      month: "8",
      day: "7",
      zh_name: "市營地下鐵御堂筋線正式通車。",
      eng_name: "Official launch of the Municipal Subway Mido Suji Line",
      jp_name: "市営地下鉄御堂筋線が正式に開通",
      display: true,
      url: "/history/railway-history/16",
      type: "internal",
    },
  ],
};

export default majorEvents;
