export interface IMajorEvents {
  data: IMajorEventData[];
}

export interface IMajorEventData {
  year: string;
  month: string;
  day: string;
  zh_name: string;
  display: boolean;
  url?: string;
  type: "internal" | "external" | "pointer";
}

const majorEvents: IMajorEvents = {
  data: [
    {
      year: "2012",
      month: "2",
      day: "1",
      zh_name: "Buddy市開荒",
      display: true,
      type: "pointer",
    },
    {
      year: "2012",
      month: "2",
      day: "2",
      zh_name: "基礎道路建成",
      display: true,
      type: "pointer",
    },
    {
      year: "2012",
      month: "2",
      day: "3",
      zh_name: "定義市政區-市中心，界定為(197,238)至(375,383)之間",
      display: true,
      url: "/building_list/0",
      type: "internal",
    },
    {
      year: "2012",
      month: "2",
      day: "20",
      zh_name:
        "定義市政區-Buddy Hill，界定為(197,238)、(405,227)、(437,373)、(360,296)之間",
      display: true,
      url: "/building_list/0",
      type: "internal",
    },
    {
      year: "2012",
      month: "3",
      day: "1",
      zh_name: "建立路名系統",
      display: true,
      type: "pointer",
    },
    {
      year: "2012",
      month: "3",
      day: "15",
      zh_name: "Buddy City 火箭發射中心落成",
      display: true,
      url: "/building_list/0/20",
      type: "internal",
    },
    {
      year: "2012",
      month: "3",
      day: "16",
      zh_name:
        "行使衛星發射升空，搭載全球定位系統、氣像監測設備，位置為(293,345)至(311,363)之間上空",
      display: true,
      type: "pointer",
    },
    {
      year: "2012",
      month: "3",
      day: "20",
      zh_name: "Buddy City體育館落成",
      display: true,
      url: "/building_list/0/3",
      type: "internal",
    },
    {
      year: "2012",
      month: "3",
      day: "25",
      zh_name: "Buddy City天文台落成，現Buddy City暨DJaLok天文台",
      display: true,
      url: "/building_list/1/6",
      type: "internal",
    },
    {
      year: "2012",
      month: "3",
      day: "27",
      zh_name: "前九廣鐵路鐘樓建成",
      display: true,
      url: "/building_list/0/0",
      type: "internal",
    },
    {
      year: "2012",
      month: "4",
      day: "1",
      zh_name: "高架鐵路一線第一期完工通車",
      display: false,
      url: "/history/railway-history/0",
      type: "internal",
    },
    {
      year: "2012",
      month: "4",
      day: "1",
      zh_name: "高架鐵路一線正式通車",
      display: true,
      url: "/history/railway-history/0",
      type: "internal",
    },
    {
      year: "2012",
      month: "5",
      day: "1",
      zh_name: "Buddy City電視城落成",
      display: true,
      url: "/building_list/0/6",
      type: "internal",
    },
    {
      year: "2012",
      month: "5",
      day: "2",
      zh_name: "高架鐵路二線第一期完工通車",
      display: false,
      url: "/history/railway-history/1",
      type: "internal",
    },
    {
      year: "2012",
      month: "5",
      day: "2",
      zh_name: "高架鐵路二線正式通車",
      display: true,
      url: "/history/railway-history/1",
      type: "internal",
    },
    {
      year: "2012",
      month: "5",
      day: "3",
      zh_name: "地下鐵路一線正式通車",
      display: false,
      url: "/history/railway-history/2",
      type: "internal",
    },
    {
      year: "2012",
      month: "5",
      day: "3",
      zh_name: "地下鐵路一線正式通車",
      display: true,
      url: "/history/railway-history/2",
      type: "internal",
    },
    {
      year: "2012",
      month: "5",
      day: "4",
      zh_name: "高架鐵路一線第二期喪屍場延線完工通車",
      display: false,
      url: "/history/railway-history/3",
      type: "internal",
    },
    {
      year: "2013",
      month: "5",
      day: "5",
      zh_name: "高架鐵路一線第二期Super Restaurant延線完工通車",
      display: false,
      url: "/history/railway-history/3",
      type: "internal",
    },
    {
      year: "2013",
      month: "5",
      day: "10",
      zh_name: "Buddy City 電車總站落成",
      display: true,
      url: "/building_list/0/7",
      type: "internal",
    },
    {
      year: "2013",
      month: "5",
      day: "11",
      zh_name: "定義市政區-北區、沙漠區",
      display: true,
      url: "/building_list/2",
      type: "internal",
    },
    {
      year: "2013",
      month: "7",
      day: "2",
      zh_name: "定義市政區-沙田區",
      display: true,
      url: "/building_list/9",
      type: "internal",
    },
    {
      year: "2017",
      month: "4",
      day: "1",
      zh_name: "定義市政區-東京區，取代部份沙漠區",
      display: true,
      url: "/building_list/4",
      type: "internal",
    },
    {
      year: "2017",
      month: "4",
      day: "2",
      zh_name: "香港中國銀行香港大廈落成",
      display: true,
      url: "/building_list/11/2",
      type: "internal",
    },
    {
      year: "2017",
      month: "4",
      day: "2",
      zh_name: "東京タワー落成",
      display: true,
      url: "/building_list/4/2",
      type: "internal",
    },
    {
      year: "2017",
      month: "4",
      day: "10",
      zh_name:
        "定義市政區-清水區，界定為現由黑目川以北、東京タワー通り以東、大阪城以西區域",
      display: true,
      url: "/building_list/5",
      type: "internal",
    },
    {
      year: "2017",
      month: "4",
      day: "11",
      zh_name: "定義市政區-樂園區，界定為現港島區、校園區以南、臺北區以北區域",
      display: true,
      url: "/building_list/8",
      type: "internal",
    },
    {
      year: "2017",
      month: "4",
      day: "13",
      zh_name: "香港中央圖書館落成",
      display: true,
      url: "/building_list/11/3",
      type: "internal",
    },
    {
      year: "2017",
      month: "4",
      day: "15",
      zh_name: "RoyHo 清水寺落成",
      display: true,
      url: "/building_list/8/0",
      type: "internal",
    },
    {
      year: "2017",
      month: "4",
      day: "16",
      zh_name: "建立地址系統、定義市政區-新市中心區，取代部份市中心區域",
      display: true,
      url: "/building_list/0",
      type: "internal",
    },
    {
      year: "2017",
      month: "4",
      day: "16",
      zh_name: "Buddy Hill 更名為 Buddy 山區",
      display: true,
      url: "/building_list/1",
      type: "internal",
    },
    {
      year: "2017",
      month: "4",
      day: "19",
      zh_name: "旋轉木馬搬遷到通天列車以南、樂園區一部份被港島區替代",
      display: true,
      url: "/building_list/8/1",
      type: "internal",
    },
    {
      year: "2017",
      month: "4",
      day: "19",
      zh_name:
        "定義市政區-港島區，取代樂園區，界定為現東京タワー通り以南、新中央區以南、樂園區以東區域",
      display: true,
      url: "/building_list/11",
      type: "internal",
    },
    {
      year: "2017",
      month: "4",
      day: "20",
      zh_name:
        "定義市政區-青衣區，取代北區。界定為由現青敬路以西、校園路以北等區域",
      display: true,
      url: "/building_list/6",
      type: "internal",
    },
    {
      year: "2017",
      month: "4",
      day: "20",
      zh_name: "青衣運動場建成",
      display: true,
      url: "/building_list/6/0",
      type: "internal",
    },
    {
      year: "2017",
      month: "4",
      day: "30",
      zh_name: "Buddy City 海濱公園落成",
      display: true,
      url: "/building_list/11/0",
      type: "internal",
    },
    {
      year: "2017",
      month: "5",
      day: "10",
      zh_name: "定義市政區-機場管轄區，取代部份沙漠區",
      display: true,
      url: "/building_list/7",
      type: "internal",
    },
    {
      year: "2017",
      month: "5",
      day: "15",
      zh_name: "高架鐵路一線第三期電車總站延線完工通車",
      display: false,
      url: "/history/railway-history/4",
      type: "internal",
    },
    {
      year: "2017",
      month: "5",
      day: "15",
      zh_name: "定義市政區-能源區",
      display: true,
      url: "/building_list/10",
      type: "internal",
    },
    {
      year: "2017",
      month: "5",
      day: "16",
      zh_name: "Buddy City暨Kai's 國際機場落成啟用",
      display: true,
      url: "/building_list/7/0",
      type: "internal",
    },
    {
      year: "2017",
      month: "5",
      day: "16",
      zh_name: "Buddy City核電站落成啟用",
      display: true,
      url: "/building_list/10/0",
      type: "internal",
    },
    {
      year: "2017",
      month: "5",
      day: "20",
      zh_name: "青馬大橋建成",
      display: true,
      url: "/building_list/7/2",
      type: "internal",
    },
    {
      year: "2017",
      month: "5",
      day: "20",
      zh_name: "定義市鎮-新Buddy市",
      display: true,
      type: "pointer",
    },
    {
      year: "2017",
      month: "5",
      day: "22",
      zh_name: "海底隧道落成啟用",
      display: true,
      url: "/building_list/10/1",
      type: "internal",
    },
    {
      year: "2017",
      month: "6",
      day: "1",
      zh_name: "路面電車第一期完工通車",
      display: false,
      url: "/history/railway-history/5",
      type: "internal",
    },
    {
      year: "2017",
      month: "6",
      day: "1",
      zh_name: "路面電車正式通車",
      display: true,
      url: "/history/railway-history/5",
      type: "internal",
    },
    {
      year: "2017",
      month: "6",
      day: "2",
      zh_name: "定義市政區-校園區。界定為由現校園路以南、中央廣場路以西等區域",
      display: true,
      url: "/building_list/3",
      type: "internal",
    },
    {
      year: "2017",
      month: "6",
      day: "6",
      zh_name: "梁植偉(樂善堂梁植偉紀念中學校舍)落成",
      display: true,
      url: "/building_list/3/0",
      type: "internal",
    },
    {
      year: "2017",
      month: "6",
      day: "10",
      zh_name: "機場快線第一期完工通車",
      display: false,
      url: "/history/railway-history/6",
      type: "internal",
    },
    {
      year: "2017",
      month: "6",
      day: "10",
      zh_name: "機場快線正式通車",
      display: true,
      url: "/history/railway-history/6",
      type: "internal",
    },
    {
      year: "2017",
      month: "6",
      day: "20",
      zh_name: "路面電車第二期Buddy City運動場及沙田區延線完工通車",
      display: false,
      url: "/history/railway-history/7",
      type: "internal",
    },
    {
      year: "2017",
      month: "6",
      day: "20",
      zh_name: "St.Mok M大教堂落成",
      display: true,
      url: "/building_list/1/10",
      type: "internal",
    },
    {
      year: "2017",
      month: "6",
      day: "21",
      zh_name: "定義市政區-軍營區",
      display: true,
      type: "pointer",
    },
    {
      year: "2017",
      month: "6",
      day: "25",
      zh_name: "浩園落成",
      display: true,
      url: "/building_list/1/11",
      type: "internal",
    },
    {
      year: "2017",
      month: "7",
      day: "12",
      zh_name: "路面電車第三期清水區延線完工通車",
      display: false,
      url: "/history/railway-history/8",
      type: "internal",
    },
    {
      year: "2017",
      month: "11",
      day: "11",
      zh_name:
        "定義市政區-大阪區，取代北區。界定為由現清水路以北、本町通以北、Buddy山徑以北等區域",
      display: true,
      url: "/building_list/12",
      type: "internal",
    },
    {
      year: "2017",
      month: "11",
      day: "13",
      zh_name: "大阪城落成",
      display: true,
      url: "/building_list/12/8",
      type: "internal",
    },
    {
      year: "2017",
      month: "11",
      day: "15",
      zh_name: "大阪城公園周邊建設落成",
      display: true,
      url: "/building_list/12/0",
      type: "internal",
    },
    {
      year: "2017",
      month: "11",
      day: "20",
      zh_name: "開始建立觀光服務網站Buddy-Info",
      display: true,
      type: "pointer",
    },
    {
      year: "2017",
      month: "11",
      day: "25",
      zh_name: "財團法人Buddy市觀光局正式成立",
      display: true,
      url: "/bcctb-about-us",
      type: "internal",
    },
    {
      year: "2018",
      month: "2",
      day: "1",
      zh_name: "Buddy City路面電車進行大型延展工程",
      display: true,
      url: "/history/railway-history/9",
      type: "internal",
    },
    {
      year: "2018",
      month: "3",
      day: "3",
      zh_name: "路面電車第四期港島區、能源區及跨海線路延線完工通車",
      display: false,
      url: "/history/railway-history/9",
      type: "internal",
    },
    {
      year: "2018",
      month: "4",
      day: "1",
      zh_name: "修建目黒川水道",
      display: true,
      url: "/building_list/4/6",
      type: "internal",
    },
    {
      year: "2018",
      month: "4",
      day: "2",
      zh_name: "目黒川沿いの桜並木修建完工",
      display: true,
      url: "/building_list/4/6",
      type: "internal",
    },
    {
      year: "2018",
      month: "4",
      day: "5",
      zh_name: "基督教醫療財團法人Buddy醫院落成",
      display: true,
      url: "/building_list/13/0",
      type: "internal",
    },
    {
      year: "2018",
      month: "4",
      day: "10",
      zh_name: "臺北101落成",
      display: true,
      url: "/building_list/13/2",
      type: "internal",
    },
    {
      year: "2018",
      month: "4",
      day: "15",
      zh_name: "Buddy市警察廳本部落成",
      display: true,
      url: "/building_list/12/5",
      type: "internal",
    },
    {
      year: "2018",
      month: "4",
      day: "20",
      zh_name: "Buddy市廳落成",
      display: true,
      url: "/building_list/12/6",
      type: "internal",
    },
    {
      year: "2018",
      month: "4",
      day: "25",
      zh_name: "Buddy市消防廳本部落成",
      display: true,
      url: "/building_list/4/7",
      type: "internal",
    },
    {
      year: "2018",
      month: "5",
      day: "3",
      zh_name: "高架鐵路二線第二期青衣區延線完工通車",
      display: false,
      url: "/history/railway-history/10",
      type: "internal",
    },
    {
      year: "2018",
      month: "5",
      day: "3",
      zh_name:
        "市營地下鐵中央線第一期正式通車、市營地下鐵阪源線第一期正式通車、市營地下鐵清水沙田線第一期正式通車",
      display: false,
      url: "/history/railway-history/10",
      type: "internal",
    },
    {
      year: "2018",
      month: "5",
      day: "3",
      zh_name: "市營地下鐵中央線、阪源線、清水沙田線正式通車",
      display: true,
      url: "/history/railway-history/10",
      type: "internal",
    },
    {
      year: "2018",
      month: "7",
      day: "5",
      zh_name:
        "機場快線第二期東京沙漠、沙田、大阪延線完工通車。路面電車第五期大阪區、目黑川及臺北區延線完工通車。",
      display: false,
      url: "/history/railway-history/11",
      type: "internal",
    },
    {
      year: "2018",
      month: "7",
      day: "15",
      zh_name: "機場快線直通車正式通車",
      display: true,
      url: "/history/railway-history/11",
      type: "internal",
    },
    {
      year: "2018",
      month: "10",
      day: "2",
      zh_name: "宏福花園落成",
      display: true,
      url: "/building_list/6/2",
      type: "internal",
    },
    {
      year: "2018",
      month: "10",
      day: "4",
      zh_name: "青衣海濱公園修建完工",
      display: true,
      url: "/building_list/6/8",
      type: "internal",
    },
    {
      year: "2018",
      month: "10",
      day: "19",
      zh_name: "青衣市政大廈落成",
      display: true,
      url: "/building_list/6/4",
      type: "internal",
    },
    {
      year: "2018",
      month: "10",
      day: "28",
      zh_name: "路面電車第六期青衣區延線完工通車",
      display: false,
      url: "/history/railway-history/12",
      type: "internal",
    },
    {
      year: "2018",
      month: "11",
      day: "9",
      zh_name: "定義市政區-臺北區。界定為由現軍營區以西、樂園區以南區域",
      display: true,
      url: "/building_list/13",
      type: "internal",
    },
    {
      year: "2021",
      month: "9",
      day: "22",
      zh_name:
        "定義市水域-維多利亞港，界定為現軍營區以東、海盜船以南水域。東京灣，界定海盜船以東，機場以西至能源區以東水域為止",
      display: true,
      type: "pointer",
    },
    {
      year: "2021",
      month: "10",
      day: "31",
      zh_name: "鐵路轉乘重組",
      display: false,
      url: "/history/railway-history/13",
      type: "internal",
    },
    {
      year: "2021",
      month: "12",
      day: "1",
      zh_name: "建立年號「友平」，諭意友好及和平，並以2012年為元年",
      display: true,
      url: "/page/basic/calendar-system-and-city-song",
      type: "internal",
    },
    {
      year: "2022",
      month: "1",
      day: "1",
      zh_name: "祝賀Buddy市成立10周年",
      display: true,
      type: "pointer",
    },
    {
      year: "2022",
      month: "6",
      day: "12",
      zh_name:
        "出現十年一遇大地震，因地殼變動而多處出現斷層，是 Buddy 市建立以來最大規模的一次災難。",
      display: true,
      type: "pointer",
    },
    {
      year: "2022",
      month: "6",
      day: "13",
      zh_name: "Buddy 山隧道、清水隧道落成啟用",
      display: true,
      type: "pointer",
    },
    {
      year: "2022",
      month: "6",
      day: "14",
      zh_name: "市中心地下街落成",
      display: true,
      type: "pointer",
    },
    {
      year: "2022",
      month: "6",
      day: "22",
      zh_name: "定義市政區-京都區，界定為清水區以東、東京區以東、沙漠區以東",
      display: true,
      url: "/building_list/14",
      type: "internal",
    },
    {
      year: "2022",
      month: "6",
      day: "23",
      zh_name: "法觀寺（八坂塔）重見天日",
      display: true,
      url: "/building_list/14/0",
      type: "internal",
    },
    {
      year: "2022",
      month: "6",
      day: "24",
      zh_name: "音羽山清水寺重見天日",
      display: true,
      url: "/building_list/14/1",
      type: "internal",
    },
    {
      year: "2022",
      month: "7",
      day: "1",
      zh_name: "修建道頓堀水道",
      display: true,
      url: "/building_list/12/12",
      type: "internal",
    },
    {
      year: "2022",
      month: "7",
      day: "1",
      zh_name: "道頓堀周邊景點落成",
      display: true,
      url: "/building_list/12/20",
      type: "internal",
    },
    {
      year: "2022",
      month: "7",
      day: "3",
      zh_name:
        "市營地下鐵中央線第二期谷町四丁目至難波延線段完工通車。雙京阪線第一期清水至京都延線段及黑目川至沙漠東京延線段完工，市營地下鐵清水沙田線重劃線路並廢線，由雙京坂線代替正式通車。市營地下鐵清源線第一期完工，市營地下鐵阪源線重劃線路，由清源線代替正式通車。路面電車第七期京都區、大阪區道頓堀延線完工通車。",
      display: false,
      url: "/history/railway-history/14",
      type: "internal",
    },
    {
      year: "2022",
      month: "7",
      day: "3",
      zh_name:
        "市營地下鐵清水沙田線重劃線路並廢線，由雙京坂線代替正式通車。市營地下鐵阪源線重劃線路，由清源線代替正式通車。",
      display: true,
      url: "/history/railway-history/14",
      type: "internal",
    },
    {
      year: "2022",
      month: "7",
      day: "10",
      zh_name:
        "BUDDY市政府正式發佈代表BUDDY市的市歌，名為《友與平》。諭意為「友好及和平」與年號一樣，祝願BUDDY市和全宇宙的人能友好與和平地生活。",
      display: true,
      url: "/page/basic/calendar-system-and-city-song",
      type: "internal",
    },
    {
      year: "2022",
      month: "7",
      day: "17",
      zh_name: "大阪クリスタルタワー完工開張。",
      display: true,
      url: "/building_list/12/25",
      type: "internal",
    },
    {
      year: "2022",
      month: "7",
      day: "17",
      zh_name:
        "市營地下鐵中央線與雙京坂線於谷町四丁目相接直通運轉，市營地下鐵清源線第二期清水至大阪商業園區延線段完工，市營地下鐵清源線，重新覆蓋大阪區，更名為阪源綠地線正式通車。路面電車第八期大阪商業園區延線段完工通車。",
      display: false,
      url: "/history/railway-history/15",
      type: "internal",
    },
    {
      year: "2022",
      month: "7",
      day: "17",
      zh_name:
        "市營地下鐵中央線與雙京坂線於谷町四丁目相接直通運轉，市營地下鐵清源線，重新覆蓋大阪區，更名為阪源綠地線正式通車。",
      display: true,
      url: "/history/railway-history/15",
      type: "internal",
    },
    {
      year: "2022",
      month: "7",
      day: "30",
      zh_name: "大阪 HEP FIVE 及大阪梅田周邊景點落成。",
      display: true,
      url: "/building_list/12/27",
      type: "internal",
    },
    {
      year: "2022",
      month: "8",
      day: "7",
      zh_name:
        "市營地下鐵雙京坂線第三期東梅田站完工通車。市營地下鐵御堂筋線第一期完工通車。路面電車第九期大阪梅田區域延線段完工通車。",
      display: false,
      url: "/history/railway-history/16",
      type: "internal",
    },
    {
      year: "2022",
      month: "8",
      day: "7",
      zh_name: "市營地下鐵御堂筋線正式通車。",
      display: true,
      url: "/history/railway-history/16",
      type: "internal",
    },
  ],
};

export default majorEvents;
