name: Deploy to GAE
on:
  push:
    branches: [master]
  pull_request:

jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest

    steps:
      - name: Set Up Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Checkout
        uses: actions/checkout@v2

      - name: NPM Install
        run: npm install && REACT_APP_API_KEY=${{ secrets.REACT_APP_API_KEY }} REACT_APP_MEASUREMENT_ID=${{ secrets.REACT_APP_MEASUREMENT_ID }} npm run build

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: app.yaml
          version: v1
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCP_CREDENTIALS }}
